name: mobile
description: Absenku Mobile app
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # HTTP client + secure storage
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  # Optional state mgmt (bisa ditambah nanti)
  # riverpod: ^2.5.1
  # hooks_riverpod: ^2.5.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true