name: mobile
description: Absenku Mobile app
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  mobile_scanner: ^5.2.3
  intl: ^0.19.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true